apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fcg
  labels:
    app: rabbitmq
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management

          ports:
            - name: amqp
              containerPort: 5672

            - name: management
              containerPort: 15672

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: fcg-shared-secret
                  key: RabbitMq__Username

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: fcg-shared-secret
                  key: RabbitMq__Password

          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 10

          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 5

          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fcg
spec:
  type: ClusterIP

  selector:
    app: rabbitmq

  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672

    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: fcg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
