apiVersion: v1
kind: Secret
metadata:
  name: fcg-shared-secret
  namespace: fcg
type: Opaque
stringData:
  Jwt__SecretKey: "ChangeMe_WithAtLeast64Characters_AndUseTheSameValueInApisAndKong_0001"
  RabbitMq__Username: "fcg"
  RabbitMq__Password: "ChangeMe_RabbitMq_123!"
  Users__ConnectionString: "Server=users-sqlserver,1433;Database=FCGUsersDb;User Id=sa;Password=ChangeMe_UsersSql_123!;TrustServerCertificate=True;Encrypt=False"
  Users__SqlPassword: "ChangeMe_UsersSql_123!"
  Catalog__ConnectionString: "Server=catalog-sqlserver,1433;Database=FCGCatalogDb;User Id=sa;Password=ChangeMe_CatalogSql_123!;TrustServerCertificate=True;Encrypt=False"
  Catalog__SqlPassword: "ChangeMe_CatalogSql_123!"
  Payments__ConnectionString: "Server=payments-sqlserver,1433;Database=FCGPaymentsDb;User Id=sa;Password=ChangeMe_PaymentsSql_123!;TrustServerCertificate=True;Encrypt=False"
  Payments__SqlPassword: "ChangeMe_PaymentsSql_123!"
  MongoDb__RootUsername: "fcg"
  MongoDb__RootPassword: "ChangeMe_MongoDb_123!"
  MongoDb__ConnectionString: "mongodb://fcg:ChangeMe_MongoDb_123!@mongodb:27017/?authSource=admin"
  Redis__Password: "ChangeMe_Redis_123!"
  Notifications__FunctionKey: "REPLACE_WITH_AZURE_FUNCTION_KEY"
  Grafana__AdminUser: "admin"
  Grafana__AdminPassword: "ChangeMe_Grafana_123!"
