apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: fcg
  labels:
    app: fcg-catalog-api
spec:
  type: LoadBalancer
  selector:
    app: fcg-catalog-api
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 8080
